name: Continuous Integration

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  avoid_reduncy:
    name: Cancel previous redundant builds
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  install_dependencies:
    name: Install dependencies
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v2
      
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm i --ignore-scripts

  build:
    needs: [install_dependencies]
    name: Build application
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v2

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm i --ignore-scripts

      - name: Install node-sass
        run: node node_modules/node-sass/scripts/install.js
      
      - name: Rebuild node-sass
        run: npm rebuild node-sass

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  install_cypress:
    name: Install Cypress
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up node 
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Cache Cypress binary
        id: cache-cypress-dependency
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-${{ hashFiles('package.json') }}
      
      - name: Cypress install
        if: steps.cache-cypress-dependency.outputs.cache-hit != 'true'
        run: npx cypress install

  run_cypress:
    needs: [build, install_cypress]
    name: End-to-end tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up node 
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: npm i --ignore-scripts

      - name: Install node-sass
        run: node node_modules/node-sass/scripts/install.js
      
      - name: Rebuild node-sass
        run: npm rebuild node-sass
      
      - name: Start server
        run: npm run start &
      
      - name: Cache Cypress binary
        id: cache-cypress-dependency
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-${{ hashFiles('package.json') }}
    
      - name: Cypress install
        if: steps.cache-cypress-dependency.outputs.cache-hit != 'true'
        run: npx cypress install
      
      - name: Run cypress tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: npm run test:e2e
          wait-on: http://localhost:3000
